# Generated by Django 5.1.4 on 2025-01-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(db_index=True)),
                ('league', models.CharField(db_index=True, max_length=100)),
                ('season', models.CharField(db_index=True, max_length=20)),
                ('home_club', models.CharField(max_length=200)),
                ('away_club', models.CharField(max_length=200)),
                ('home_score', models.PositiveIntegerField()),
                ('away_score', models.PositiveIntegerField()),
            ],
        ),
    ]
