# Generated by Django 5.1.4 on 2025-01-03 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches_table', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='away_club',
            new_name='away',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='home_club',
            new_name='home',
        ),
    ]
