# Generated by Django 5.1.4 on 2025-01-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_table', '0002_rename_away_club_match_away_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='home',
            field=models.CharField(max_length=100),
        ),
    ]
