# Generated by Django 5.1.4 on 2025-01-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_table', '0003_alter_match_away_alter_match_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='match',
            name='home',
            field=models.CharField(max_length=200),
        ),
    ]
