# Generated by Django 5.1.4 on 2025-01-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_table', '0004_alter_match_away_alter_match_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='match',
            table='matches_table_match',
        ),
    ]
